ROOT_PATH = ../../..

EXTRASRC = ./pgm_import.c

OUT_PATH = ../data
OUT_FILES = *out*.pgm

BASE = sift

EXECS = check_output $(BASE)_normalized

EXEC = ./$(BASE)_normalized.x ../data/SIFT-car.pgm

include $(ROOT_PATH)/makefile_common
