ROOT_PATH = ../../../..

OUT_PATH = ../../data
OUT_FILES = *out*.dat

BASE = nbody_2arr

PATH1 = $(BASE)_1_1
PATH2 = $(BASE)_2_2 $(BASE)_2_3
PATH3 = $(BASE)_3_2 $(BASE)_3_3 $(BASE)_3_4 $(BASE)_3_5 $(BASE)_3_6
PATH4 = $(BASE)_4_45
# $(BASE)_4_9 $(BASE)_4_10 $(BASE)_4_11 $(BASE)_4_12 $(BASE)_4_18 $(BASE)_4_19 $(BASE)_4_20 $(BASE)_4_21 $(BASE)_4_27 $(BASE)_4_28 $(BASE)_4_29 $(BASE)_4_35 $(BASE)_4_38 $(BASE)_4_41 $(BASE)_4_42 $(BASE)_4_43 $(BASE)_4_44 $(BASE)_4_45

PATH5 = $(BASE)_5_40
# $(BASE)_5_6 $(BASE)_5_7 $(BASE)_5_8 $(BASE)_5_11 $(BASE)_5_12 $(BASE)_5_15 $(BASE)_5_18 $(BASE)_5_19 $(BASE)_5_31 $(BASE)_5_34 $(BASE)_5_37 $(BASE)_5_38 $(BASE)_5_39 $(BASE)_5_40

PATH6 = $(BASE)_6_47 $(BASE)_6_52
#$(BASE)_6_19 $(BASE)_6_20 $(BASE)_6_23 $(BASE)_6_24 $(BASE)_6_27 $(BASE)_6_30 $(BASE)_6_33 $(BASE)_6_36 $(BASE)_6_37 $(BASE)_6_38 $(BASE)_6_41 $(BASE)_6_42 $(BASE)_6_43 $(BASE)_6_44 $(BASE)_6_46 $(BASE)_6_47 $(BASE)_6_52

PATH7 = $(BASE)_7_55_maxj
# $(BASE)_7_55
# $(BASE)_7_24 $(BASE)_7_25 $(BASE)_7_26 $(BASE)_7_27 $(BASE)_7_30 $(BASE)_7_33 $(BASE)_7_36 $(BASE)_7_37 $(BASE)_7_40 $(BASE)_7_41 $(BASE)_7_42 $(BASE)_7_43 $(BASE)_7_45 $(BASE)_7_46 $(BASE)_7_50 $(BASE)_7_51 $(BASE)_7_52 $(BASE)_7_53 $(BASE)_7_54 

EXECS = check_output generate_input nbody_initial $(BASE)_normalized $(PATH7)
# $(PATH1) $(PATH2) $(PATH3) $(PATH4) $(PATH6)

EXEC = ./$(PATH7).x

include $(ROOT_PATH)/makefile_common
